Repository dmno-dev/varlock, pull requests merged in 2025-07, with the labels that each got.

#47 Add @defaultRequired=infer and associated tests
  .changeset/tidy-clouds-follow.md
  package.json
  packages/env-graph/src/lib/config-item.ts
  packages/env-graph/test/root-decorators.test.ts
  pnpm-lock.yaml
Labels: maintainer

#49 add @disabled root decorator and associated tests
  .changeset/fifty-clubs-unite.md
  .cursor/rules/env-graph-tests.mdc
  .cursor/rules/root-decorator-tests.mdc
  packages/env-graph/src/lib/config-item.ts
  packages/env-graph/src/lib/env-graph.ts
  packages/env-graph/test/disabled-decorator.test.ts
  packages/env-graph/test/required-decorators.test.ts
Labels: maintainer

#51 fix preview release action
  packages/env-spec-parser/package.json
  packages/varlock/package.json
  scripts/release-preview.js
Labels: maintainer, varlock, parser

#53 add license
  LICENSE
Labels: maintainer

#52 @defaultSensitive=inferFromPrefix(...) option and associated tests
  .changeset/eighty-worlds-repeat.md
  packages/env-graph/src/lib/config-item.ts
  packages/env-graph/test/sensitive-decorator.test.ts
Labels: maintainer

#54 add docs for new root decorators and options
  packages/varlock-website/src/content/docs/reference/root-decorators.mdx
Labels: documentation, maintainer, docs

#56 env-flag-handling
  .changeset/busy-candles-nail.md
  .changeset/evil-dingos-follow.md
  .vscode/launch.json
  example-repo/.env.development
  example-repo/.env.preview
  example-repo/.env.production
  example-repo/.env.schema
  example-repo/.env.staging
  example-repo/.env.test
  example-repo/.gitignore
  example-repo/env.d.ts
  package.json
  packages/env-graph/package.json
  packages/env-graph/src/lib/config-item.ts
  packages/env-graph/src/lib/data-source.ts
  packages/env-graph/src/lib/env-graph.ts
  packages/env-graph/src/lib/loader.ts
  packages/env-graph/src/lib/resolver.ts
  packages/env-graph/test/resolvers.test.ts
  packages/env-spec-parser/grammar.peggy
  packages/env-spec-parser/src/simple-resolver.ts
  packages/env-spec-parser/test/functions.test.ts
  packages/varlock/package.json
  packages/varlock/src/cli/commands/load.command.ts
  packages/varlock/src/lib/load-graph.ts
  packages/vscode-plugin/.env.example
  packages/vscode-plugin/language/env-spec.tmLanguage.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: maintainer, varlock, parser, vscode-plugin

#58 use varlock in varlock-website code
  packages/env-graph/src/lib/env-graph.ts
  packages/varlock-website/.env.schema
  packages/varlock-website/.gitignore
  packages/varlock-website/astro.config.mjs
  packages/varlock-website/package.json
  packages/varlock-website/src/components/EmailSignup.vue
  pnpm-lock.yaml
Labels: maintainer, docs

#59 remap, regex, --env flag docs
  packages/varlock-website/src/content/docs/guides/environments.mdx
  packages/varlock-website/src/content/docs/reference/cli-commands.mdx
  packages/varlock-website/src/content/docs/reference/functions.mdx
  packages/varlock-website/src/content/docs/reference/root-decorators.mdx
Labels: maintainer

#42 first version of nextjs integration
  .changeset/spotty-icons-wonder.md
  .cursor/rules/add-docs-page.mdc
  .cursor/rules/style-guide.mdc
  packages/integrations/nextjs/README.md
  packages/integrations/nextjs/package.json
  packages/integrations/nextjs/src/next-env-compat.ts
  packages/integrations/nextjs/src/patch-next-runtime.ts
  packages/integrations/nextjs/src/plugin.ts
  packages/integrations/nextjs/tsconfig.json
  packages/integrations/nextjs/tsup.config.ts
  packages/varlock-website/astro.config.mjs
  packages/varlock-website/package.json
  packages/varlock-website/public/_redirects
  packages/varlock-website/src/components/Badge.astro
  packages/varlock-website/src/content/docs/guides/environments.mdx
  packages/varlock-website/src/content/docs/guides/integration.mdx
  packages/varlock-website/src/content/docs/guides/migrate-from-dotenv.mdx
  packages/varlock-website/src/content/docs/integrations/esbuild.mdx
  packages/varlock-website/src/content/docs/integrations/javascript.mdx
  packages/varlock-website/src/content/docs/integrations/nextjs.mdx
  packages/varlock-website/src/content/docs/integrations/other-languages.mdx
  packages/varlock-website/src/content/docs/reference/functions.mdx
  packages/varlock-website/src/content/docs/reference/item-decorators.mdx
  packages/varlock-website/src/content/docs/reference/root-decorators.mdx
  packages/varlock-website/src/styles/global.css
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: maintainer, docs, varlock

#45 generalized AI docs including meta rules in our repo
  .cursorignore
  example-repo-init/.cursorignore
  packages/varlock-website/astro.config.mjs
  packages/varlock-website/src/content/docs/guides/ai-tools.mdx
  packages/varlock-website/src/content/docs/guides/cursor.mdx
Labels: maintainer, docs

#50 [Changesets] Versioned release
  .changeset/busy-candles-nail.md
  .changeset/dirty-bars-clap.md
  .changeset/eighty-worlds-repeat.md
  .changeset/evil-dingos-follow.md
  .changeset/evil-foxes-decide.md
  .changeset/fifty-clubs-unite.md
  .changeset/old-beans-punch.md
  .changeset/spotty-icons-wonder.md
  .changeset/tidy-clouds-follow.md
  packages/env-spec-parser/CHANGELOG.md
  packages/env-spec-parser/package.json
  packages/integrations/nextjs/CHANGELOG.md
  packages/integrations/nextjs/package.json
  packages/varlock/CHANGELOG.md
  packages/varlock/package.json
Labels: maintainer, varlock, parser

#61 republish v0.0.3
  .changeset/chilly-houses-design.md
Labels: maintainer

#66 add star us component
  packages/varlock-website/astro.config.mjs
  packages/varlock-website/src/components/SocialIcons.astro
  packages/varlock-website/src/components/StarArrow.vue
Labels: maintainer, docs

#69 fix override docs
  eslint.config.mjs
  package.json
  packages/eslint-custom-rules/index.js
  packages/eslint-custom-rules/package.json
  packages/eslint-custom-rules/rules/prefer-const.js
  packages/integrations/nextjs/README.md
  packages/integrations/nextjs/package.json
  packages/varlock-website/astro.config.mjs
  packages/varlock-website/src/content/docs/guides/migrate-from-dotenv.mdx
  packages/varlock-website/src/content/docs/integrations/nextjs.mdx
  packages/varlock-website/src/styles/global.css
  packages/varlock/package.json
  pnpm-lock.yaml
Labels: maintainer, docs, varlock

#70 actually fix varlock.dev robots.txt
  packages/varlock-website/astro.config.ts
  packages/varlock-website/src/content/docs/guides/ai-tools.mdx
  packages/varlock-website/src/content/docs/integrations/javascript.mdx
  packages/varlock-website/src/content/docs/integrations/nextjs.mdx
  turbo.json
Labels: maintainer, docs

#79 next integration + docs improvements
  .changeset/moody-crabs-fry.md
  CONTRIBUTING.md
  packages/env-graph/src/lib/env-graph.ts
  packages/integrations/nextjs/README.md
  packages/integrations/nextjs/package.json
  packages/integrations/nextjs/src/next-env-compat.ts
  packages/integrations/nextjs/tsup.config.ts
  packages/varlock-website/src/content/docs/env-spec/reference.mdx
  packages/varlock-website/src/content/docs/getting-started/installation.mdx
  packages/varlock-website/src/content/docs/integrations/nextjs.mdx
  packages/varlock-website/src/content/docs/reference/item-decorators.mdx
  packages/varlock-website/src/content/docs/reference/root-decorators.mdx
  packages/varlock/src/cli/commands/init.command.ts
  packages/varlock/src/cli/helpers/js-package-manager-utils.ts
  packages/varlock/src/cli/helpers/pretty-format.ts
  packages/varlock/src/runtime/env.ts
Labels: maintainer

#82 add discord link and some layout tweaks
  packages/varlock-website/astro.config.ts
  packages/varlock-website/src/components/SocialIcons.astro
  packages/varlock-website/src/components/StarArrow.vue
  packages/varlock-website/src/styles/global.css
Labels: maintainer, docs

#86 fix next integration dev reloading
  .changeset/fifty-points-buy.md
  packages/integrations/nextjs/src/next-env-compat.ts
  packages/integrations/nextjs/src/plugin.ts
Labels: maintainer

#88 update load help output to show all formats
  .changeset/social-chefs-drive.md
  packages/varlock/src/cli/commands/load.command.ts
Labels: maintainer

#92 fix typo
  packages/varlock/src/cli/cli-executable.ts
Labels: community

#103 chore: update dependencies
  .changeset/config.json
  .changeset/fuzzy-cooks-sip.md
  .github/dependabot.yml
  .github/workflows/binary-release.yaml
  .github/workflows/pr-labeler.yaml
  .github/workflows/release-preview.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  example-monorepo/packages/basic/package.json
  example-monorepo/packages/qwik-example/package.json
  example-monorepo/packages/vite-vue-example/package.json
  example-monorepo/pnpm-lock.yaml
  example-repo-init/package.json
  example-repo-init/pnpm-lock.yaml
  package.json
  packages/env-spec-parser/package.json
  packages/integrations/vite/package.json
  packages/varlock-website/package.json
  packages/varlock/package.json
  packages/vscode-plugin/package.json
  pnpm-lock.yaml
Labels: maintainer, docs, varlock, parser, vscode-plugin, vite-integration

#98 add internal exports for env-graph and associated
  .changeset/brown-parks-repeat.md
  packages/env-graph/src/index.ts
  packages/varlock/src/cli/helpers/error-checks.ts
  packages/varlock/src/index.ts
Labels: maintainer
