Repository dmno-dev/varlock, pull requests merged in 2025-09, with the labels that each got.

#138 remove envFlag normalization
  .changeset/slick-eyes-teach.md
  packages/varlock/env-graph/lib/data-source.ts
Labels: maintainer

#125 MVP varlock GitHub action
  .changeset/pink-symbols-appear.md
  packages/varlock-github-action/README.md
  packages/varlock-website/astro.config.ts
  packages/varlock-website/src/content/docs/guides/environments.mdx
  packages/varlock-website/src/content/docs/integrations/github-action.mdx
  packages/varlock-website/src/content/docs/reference/root-decorators.mdx
  packages/varlock/env-graph/lib/env-graph.ts
  pnpm-lock.yaml
Labels: maintainer, docs

#136 @required - env() helper
  .changeset/thin-parents-lick.md
  packages/varlock/env-graph/lib/config-item.ts
  packages/varlock/env-graph/lib/type-generation.ts
  packages/varlock/env-graph/test/required-decorators.test.ts
  packages/varlock/env-graph/test/resolvers.test.ts
Labels: maintainer

#159 support windows-style newlines
  .changeset/plain-feet-unite.md
  packages/env-spec-parser/src/index.ts
  packages/env-spec-parser/test/general.test.ts
Labels: maintainer

#158 allow setting envFlag from imported file
  .changeset/early-rockets-do.md
  packages/varlock/env-graph/lib/data-source.ts
  packages/varlock/env-graph/lib/env-graph.ts
  packages/varlock/env-graph/test/environments.test.ts
  packages/varlock/env-graph/test/import.test.ts
Labels: maintainer

#161 [Changesets] Versioned release
  .changeset/dirty-weeks-boil.md
  .changeset/early-rockets-do.md
  .changeset/plain-feet-unite.md
  .changeset/rich-flies-march.md
  .changeset/slimy-groups-unite.md
  packages/env-spec-parser/CHANGELOG.md
  packages/env-spec-parser/package.json
  packages/integrations/astro/CHANGELOG.md
  packages/integrations/astro/package.json
  packages/integrations/nextjs/CHANGELOG.md
  packages/integrations/nextjs/package.json
  packages/integrations/vite/CHANGELOG.md
  packages/integrations/vite/package.json
  packages/varlock/CHANGELOG.md
  packages/varlock/package.json
Labels: maintainer, varlock, parser, nextjs-integration, vite-integration
